// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYAhwOEfqvAqO74PkJLt8NL1G1VHlCTVE',
    appId: '1:787328790336:web:64ac51fc0d771968f054a5',
    messagingSenderId: '787328790336',
    projectId: 'cmsc23-u2l-project',
    authDomain: 'cmsc23-u2l-project.firebaseapp.com',
    storageBucket: 'cmsc23-u2l-project.appspot.com',
    measurementId: 'G-SSJXSQFKBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYwjbaicRJp4DSdL-aLQlH3FX8vsc07U',
    appId: '1:787328790336:android:fa2e9aa18873daeaf054a5',
    messagingSenderId: '787328790336',
    projectId: 'cmsc23-u2l-project',
    storageBucket: 'cmsc23-u2l-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGf1XXa0CMguG-0y8h9rkxtx1P7UfQ7Rk',
    appId: '1:787328790336:ios:45670f12da3c6475f054a5',
    messagingSenderId: '787328790336',
    projectId: 'cmsc23-u2l-project',
    storageBucket: 'cmsc23-u2l-project.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGf1XXa0CMguG-0y8h9rkxtx1P7UfQ7Rk',
    appId: '1:787328790336:ios:45670f12da3c6475f054a5',
    messagingSenderId: '787328790336',
    projectId: 'cmsc23-u2l-project',
    storageBucket: 'cmsc23-u2l-project.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYAhwOEfqvAqO74PkJLt8NL1G1VHlCTVE',
    appId: '1:787328790336:web:6bfa2b379a6c1069f054a5',
    messagingSenderId: '787328790336',
    projectId: 'cmsc23-u2l-project',
    authDomain: 'cmsc23-u2l-project.firebaseapp.com',
    storageBucket: 'cmsc23-u2l-project.appspot.com',
    measurementId: 'G-69SZD5G186',
  );
}
